Feature: add donation confirmation settings UI
impress-org/givewp-next-gen pull request #237
Opened 2023-07-28 20:33 UTC by jonwaldstein

…confirmation setting with popover and template tags

## Description

This updates the donation confirmation settings UI with a popover and list of available template tags.

## Affects

The donation confirmation settings UI in the form builder.

## Visuals

<img width="714" alt="Screenshot 2023-07-28 at 4 31 55 PM" src="https://github.com/impress-org/givewp-next-gen/assets/10138447/f050279e-6e0c-4463-9d0c-527f5e7a5896">

## Testing Instructions

- Build assets and view a donation form builder
- Interact with the donation confirmation settings

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-08-07 20:14 UTC, jonwaldstein commented
@glaubersilva this ready for review.

2023-08-09 19:11 UTC, glaubersilva requested changes
@jonwaldstein Great work! About the code, I left just one comment about a minor change. 

But about the feature itself, we have a few things to take care of:

1. The line breaks don't work on the confirmation page
2. The P2P tags are loaded, but next gen will be released without compatibility with the v3 forms, more details here: https://github.com/impress-org/give-peer-to-peer/pull/505
3. The PDF receipt link is using the same color as the header background and because of that seems to not be present at the first look. 

Check the attached screenshot for visual reference:

![tag-problems](https://github.com/impress-org/givewp-next-gen/assets/16308864/174b347d-104b-442e-962b-12a25e81e9ea)

2023-08-09 19:51 UTC, jonwaldstein commented
@glaubersilva thanks for brining these up.  I discovered a few things:

1. _The line breaks don't work on the confirmation page_: they actually do! but some tags like pdf_receipt is making it not work.  It might be a setting on Interweave or the way we handle converting tags with links. I'll look into that.
2. _The P2P tags are loaded, but next gen will be released without compatibility with the v3 form..._ we can try to filter those out - i'll look into that.
3. Ah yeah, we can add a little styling help for links on the classic design

2023-08-09 20:59 UTC, jonwaldstein commented on src/FormBuilder/resources/js/form-builder/src/settings/donation-confirmation/index.tsx
> +        <PanelBody title={__('Donation Confirmation')} initialOpen={false}>
resolved 4bab9e37

2023-08-09 21:02 UTC, jonwaldstein commented
@glaubersilva okay man I fixed those main issues.

- Added nl2br for the content so interweave can handle line breaks appropriately alongside anchor tags
- Filtered available tag list
- Styling for me was okay on the link, let's add a QA item to make the confirmation page smarter for contrast in background color and text.  Right now it's going to depend on the design options.

<img width="794" alt="Screenshot 2023-08-09 at 4 57 04 PM" src="https://github.com/impress-org/givewp-next-gen/assets/10138447/4af0a68c-b6b4-4233-bfca-8411c0f25015">

2023-08-10 14:30 UTC, glaubersilva commented
@jonwaldstein Thanks for the changes, now the line breaks are working, but the link keeps the same background color on my end. About the P2P tags, a weird bug is happening when the addon is activated, check the video to see what's happening: https://www.loom.com/share/ec528d56ae124311809fcd6067b80ffe

2023-08-10 15:27 UTC, jonwaldstein commented
> @jonwaldstein Thanks for the changes, now the line breaks are working, but the link keeps the same background color on my end. About the P2P tags, a weird bug is happening when the addon is activated, check the video to see what's happening: https://www.loom.com/share/ec528d56ae124311809fcd6067b80ffe

@glaubersilva I just pushed a fix for the p2p conflict.  please try again.

2023-08-10 21:44 UTC, merged